### PR TITLE
Readability issue on darkui

### PR DESCRIPTION
**Pull request by PEM--**
Dark ui set color as whitish. Ensuring a fullscreen approach and modifying color ensures readability.

### CODE REVIEW

**Comment by gadicc** [comment]
The man's on a roll :D

**Comment by PEM--** [comment]
Nothing fancy. It was late and, therefore, a bit harsh on my eyes. I'm sure that you know the feeling :wink:

**Comment by PEM--** [comment]
@gadicc, You closed it instead of merging it. There was a problem about it or you're on your way for creating something else?

**Comment by gadicc** [comment]
The problem was with me I think :>

**Pull request merged**
